CREATE TABLE KATEGORI (KATEGORI_REFNO INT NOT NULL PRIMARY KEY IDENTITY (1,1),KATEGORI_ADI VARCHAR (50) NOT NULL)

CREATE TABLE KITAP (KITAP_REFNO INT NOT NULL PRIMARY KEY IDENTITY (1,1),ADI VARCHAR (50) NOT NULL,YAZARI VARCHAR (50) NOT NULL,ALIS_FIYATI INT NOT NULL,SATIS_FIYATI INT NOT NULL,YAYIN_YILI NUMARIC (40) NOT NULL,KATEGORI_REFNO INT NULL FOREIGN KEY REFERENCES KATEGORI(KATEGORI_REFNO),OZET VARCHAR (200) NOT NULL)

CREATE TABLE UYE (UYE_REFNO INT NOT NULL PRIMARY KEY IDENTITY (1,1),ADI_SOYADI VARCHAR (50) NOT NULL,SIFRE VARCHAR (20) NOT NULL,DURUMU BIT NOT NULL)

CREATE TABLE DURUMU (DURUMU_REFNO INT NOT NULL PRIMARY KEY IDENTITY (1,1),ACIKLAMA VARCHAR (200) NOT NULL)

CREATE TABLE SIPARIS (SIPARIS_REFNO INT NOT NULL PRIMARY KEY IDENTITY (1,1),UYE_REFNO INT NOT NULL FOREIGN KEY REFERENCES UYE(UYE_UYE_REFNO),TARIH DATE NOT NULL,DURUMU_REFNO INT NOT NULL FOREIGN KEY REFERENCES DURUMU(DURUMU_REFNO)

CREATE TABLE SIP_DETAY (SIP_DETAY_REFNO INT NOT NULL PRIMARY KEY IDENTITY (1,1),SIPARIS_REFNO INT NOT NULL FOREIGN KEY REFERENCES SIPARIS(SIPARIS_REFNO),KITAP_REFNO INT OT NULL,ALIS_FIYATI INT NOT NULL,SATIS_FIYATI INT DEFAULT,ADET INT NOT NULL)

--5 adet kategori giriniz.
INSERT INTO KATEGORI(KATEGORI_ADI) VALUES('Yazýlým'), ('Çocuk'), ('Edebiyat'), ('Hobi') ('Dini')

--Her bir kategori için birer kitap giriniz.
INSERT INTO KITAP 
(KATEGORI_REFNO, ADI,YAZARI, ALIS_FIYATI, SATIS_FIYATI,YAYIN_YILI, OZET) VALUES(1,'Csharp','Müzeyyen',50,0,2019,'Yazýlým Kitabý'),
(2,'Kurallara uymak güzel', 'Münir''e Þafak',5,0,2014,'Masallarla görgü kitabý'),
(3,'Çalýkuþu','Reþat Nuri Güntekin',50,0,2000,'Edebiyat Kitabý'),
(4,'Burçlar','Tutku Yayýnevi',18,0,2015,'Ayrýntýlý burç bilgileri'),
(5,'Aþkýn Gözyaþlarý', 'Sinan Yaðmur',22,0,2010,'Dini kitap')

--SATIS Fiyat’ýný ALIS_FIYAT’ýna %15 oranýnda ekleme yaparak giren sql kodunu _ yazýnýz.
UPDATE KITAP SET SATIS_FIYATI=ALIS_FIYATI+(ALIS_FIYATI*15) /100;

--5 adet üye ekleyin.
INSERT INTO UYE (ADI_SOYADI, SIFRE, DURUMU) VALUES ('Müzeyyen','123',1), ('Ýrem','456',0),('Burcu','789',1), ('Selma','458',1), ('Ayþe','879',0)

--DURUMU tablosuna;
--Yeni Sipariþ, Hazýrlanýyor, Temin edilemedi, Kargoya verildi, Teslim Edildi          
--Bilgilerini ekleyen sql kodlarýný ekleyiniz.
INSERT INTO DURUMU(ACIKLAMA) VALUES ('Yeni sipariþ'), ('Hazýrlanýyor'), ('Temin Edilemedi'), ('Kargoya verildi'), ('Teslim edildi')

--Bir üye seçiliyor. Bu üye ilk 2 kitaptan 3’er adet sipariþ veriyor. Ýlgili sql kodlarýný yazarak sipariþi oluþturunuz.
INSERT INTO SIPARIS (UYE_REFNO, TARIH, DURUMU_REFNO) VALUES (1, GETDATE (),1)
INSERT INTO SIP_DETAY (SIPARIS_REFNO, KITAP_REFNO, ALIS_FIYATI, SATIS_FIYATI, ADET) VALUES ( 1, 2, 50, 58, 3), ( 1, 5, 20, 23, 3)

--Aþaðýdaki sipariþ listesini oluþturunuz.
     --ADI_SOYADI     SIPARIS_TARIHI
     --Müzeyyen Bütün          01.01.2018
     --Burcu Yýldýrým             01.02.2018
     --Ýrem Görgün                 01.03.2018
SELECT UYE.ADI_SOYADI, SIPARIS.TARIH AS SIPARIS_TARIH FROM UYE JOIN SIPARIS ON UYE.UYE_REFNO=SIPARIS.UYE_REFNO

--Kim hangi kitabý aldý listesini görüntüleyiniz.
SELECT UYE.ADI_SOYADI, KITAP.ADI AS KÝTAP_ADI FROM UYE JOIN SIPARIS ON UYE.UYE_REFNO=SIPARIS.UYE_REFNO JOIN SIP_DETAY ON 
SIPARIS.SIPARIS_REFNO=SIP_DETAY.SIPARIS_REFNO JOIN KITAP ON SIP_DETAY.KITAP_REFNO=KITAP.KITAP_REFNO

--Hangi kitap hangi kategoride listesini görüntüleyiniz.
SELECT KITAP.ADI AS KITAP_ADI, KATEGORI.KATEGORI_ADI FROM KITAP JOIN KATEGORI ON KITAP.KATEGORI_REFNO=KATEGORI.KATEGORI_REFNO
